#!/usr/bin/env python3 -u

# SPDX-FileCopyrightText: The vmnet-helper authors
# SPDX-License-Identifier: Apache-2.0

"""
Run a vm with vmnet-helper.
"""

import argparse
import ipaddress
import logging
import os
import random
import signal
import sys
import uuid

import testing

VMNET_OFFLOAD_AUTO = {
    "vfkit": "off",
    "krunkit": "off",
    "qemu": "off",
}


def main():
    shared_interfaces = testing.shared_interfaces()
    p = argparse.ArgumentParser(description="Run virtual machine using vmnet-helper")

    # Main arguments

    p.add_argument("vm_name", help="VM name")
    p.add_argument(
        "--connection",
        choices=["fd", "socket", "runner"],
        default="fd",
        help="How to connect the helper and vm (fd)",
    )

    # Helper arguments

    p.add_argument(
        "--operation-mode",
        choices=testing.OPERATION_MODES,
        help="vmnet operation mode",
    )
    p.add_argument(
        "--start-address",
        help=(
            "The starting IPv4 address (string) to use for the interface. This "
            "address is used as the gateway address. The subsequent address up "
            "to and including --end-address_key are placed in the DHCP pool. All "
            "other addresses are available for static assignment. "
            "The address must be in the private IP range (RFC 1918)."
        ),
    )
    p.add_argument(
        "--end-address",
        help=(
            "The DHCP IPv4 range end address (string) to use for the interface. "
            "The address must be in the private IP range (RFC 1918)."
        ),
    )
    p.add_argument(
        "--subnet-mask", help="The IPv4 subnet mask (string) to use on the interface."
    )
    p.add_argument(
        "--network-id",
        type=validate_uuid,
        help=(
            "The identifier (UUID) of the host network to use on the interface "
            "(host operation-mode only). The host bits of the IP address assigned "
            "to the VM are defined using a random number generator seeded from the "
            "name of the VM. See assign_ip_address for details. Changes to the static "
            "IP address between runs are not propagated, and you should manually delete "
            "the disk.img and cidata.iso files for the VM to be reachable."
        ),
    )
    p.add_argument(
        "--shared-interface",
        choices=shared_interfaces,
        default=shared_interfaces[0],
        help=f"vmnet shared interface for --operation-mode=bridged ({shared_interfaces[0]})",
    )
    p.add_argument(
        "--enable-isolation",
        action="store_true",
        help="Isolate the guest from other guests on the vmnet interface, requires --operation-mode=host",
    )
    p.add_argument(
        "--enable-offloading",
        action="store_true",
        help="Enable vmnet tso and checksum-offload options (krunkit driver only)",
    )
    p.add_argument(
        "--network",
        dest="network_name",
        metavar="NAME",
        help="Join a network managed by vmnet-broker (macOS 26 only)",
    )

    # VM arguments

    p.add_argument(
        "--driver",
        metavar="NAME",
        choices=testing.DRIVERS,
        default=testing.DRIVERS[0],
        help=f"VM driver ({testing.DRIVERS[0]})",
    )
    p.add_argument(
        "--driver-command",
        metavar="COMMAND",
        help=f"Use custom driver command",
    )
    p.add_argument(
        "--cpus",
        metavar="N",
        type=cpus,
        default=2,
        help="Number of vpus (2)",
    )
    p.add_argument(
        "--memory",
        metavar="M",
        type=int,
        default=1024,
        help="Memory size in MiB (1024)",
    )
    p.add_argument(
        "--timeout",
        metavar="SECONDS",
        type=int,
        default=60,
        help="Time to wait for VM IP address (60 seconds)",
    )

    distros = list(testing.IMAGES.keys())
    p.add_argument(
        "--distro",
        choices=distros,
        default=distros[0],
        help=f"Linux distro ({distros[0]})",
    )

    p.add_argument(
        "--dns-servers",
        metavar="ADDR",
        type=ip_list,
        default=["8.8.8.8", "1.1.1.1"],
        help="Comma-separated DNS servers for the VM (8.8.8.8,1.1.1.1)",
    )

    # Debugging

    p.add_argument("-v", "--verbose", action="store_true", help="Be more verbose")

    args = p.parse_args()
    setup_logging(args.verbose)

    if args.network_name:
        if args.operation_mode:
            p.error("--network cannot be used with --operation-mode")
        if args.start_address:
            p.error("--network cannot be used with --start-address")
        if args.end_address:
            p.error("--network cannot be used with --end-address")
        if args.subnet_mask:
            p.error("--network cannot be used with --subnet-mask")
        if args.network_id:
            p.error("--network cannot be used with --network-id")

    if args.operation_mode == "bridged":
        if not args.shared_interface:
            p.error("--shared-interface required for --operation-mode=bridged")
        if args.enable_isolation:
            p.error("--enable-isolation not compatible with --operation-mode=bridged")
        if args.network_id:
            p.error("--network-id is not compatible with --operation-mode=bridged")
    elif args.operation_mode == "shared":
        if args.network_id:
            p.error("--network-id is not compatible with --operation-mode=shared")

    if args.network_id and args.connection == "runner":
        # Without an option to set the host address, --network-id cannot be used with
        # --connection=runner
        p.error("--network-id is not compatible with --connection=runner")

    signal.signal(signal.SIGTERM, terminate)
    signal.signal(signal.SIGINT, terminate)

    if args.connection == "fd":
        run_with_fd(args)
    elif args.connection == "socket":
        run_with_socket(args)
    elif args.connection == "runner":
        run_with_runner(args)


class SecondsFormatter(logging.Formatter):
    def format(self, record):
        record.seconds = record.relativeCreated / 1000.0
        return super().format(record)


def setup_logging(verbose=False):
    formatter = SecondsFormatter("[%(seconds)8.3f] %(levelname)s %(message)s")
    handler = logging.StreamHandler(stream=sys.stdout)
    handler.setFormatter(formatter)
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(handlers=[handler], level=level)


def run_with_fd(args):
    """
    Use file descriptor passing to connect the vm and the helper.
    """
    # Create a socketpair for the child processes. The vm_sock will be used by
    # the vm, and the host_sock will be used by the helper.
    vm_sock, helper_sock = testing.socketpair()

    # Start vmnet-helper first, since we need the MAC address before starting
    # the VM.
    helper = testing.Helper(args, fd=helper_sock.fileno())
    helper.start()
    try:
        # Start the VM with the MAC address and the second socket.
        vm = testing.VM(
            args,
            helper.interface[testing.VMNET_MAC_ADDRESS],
            ip_address=assign_ip_address(helper, args),
            fd=vm_sock.fileno(),
        )
        vm.start()
        try:
            vm.wait_until_ready(timeout=args.timeout)
            os.wait()
        finally:
            vm.stop()
    finally:
        helper.stop()


def run_with_socket(args):
    """
    Use unix socket to connect the vm and the helper.
    """
    # The helper will create a unix datagram socket at this path and wait for
    # client connection.
    socket = testing.vm_path(args.vm_name, "vmnet.sock")

    # Start vmnet-helper first, since we need the MAC address before starting
    # the VM.
    helper = testing.Helper(args, socket=socket)
    helper.start()
    try:
        # Start the VM with the MAC address and the socket path.
        vm = testing.VM(
            args,
            helper.interface[testing.VMNET_MAC_ADDRESS],
            ip_address=assign_ip_address(helper, args),
            socket=socket,
        )
        vm.start()
        try:
            vm.wait_until_ready(timeout=args.timeout)
            os.wait()
        finally:
            vm.stop()
    finally:
        helper.stop()


def run_with_runner(args):
    """
    Use vmnet-run to run a vm with fd.
    """
    vm = testing.VM(
        args, testing.mac_address_from(args.vm_name), fd=4, runner=testing.RUNNER
    )
    vm.start()
    try:
        vm.wait_until_ready(timeout=args.timeout)
        os.wait()
    finally:
        vm.stop()


def ip_list(s):
    # TODO: validate that values are IP addresses.
    return s.split(",")


def cpus(s):
    n = int(s)
    if n < 1:
        raise ValueError(f"Invalid number of cpus: '{s}'")
    return n


def terminate(signo, frame):
    sys.exit(1)


def validate_uuid(arg):
    parsed = uuid.UUID(arg)
    if parsed == uuid.NIL:
        raise ValueError("Nil UUID will be ignored")
    return parsed


def assign_ip_address(helper, args):
    """
    Assigns an IP address from the helper's range based on the name of the VM.

    Returns None if --network-id is not set.

    This does not prevent address collisions on its own, but it allows the caller to set VM
    names that will result in unique addresses being set on a subnet of a known size. Using the
    repl for example, we can ensure the names "test0" and "test1" result in unique addresses on
    any network with the subnet mask 255.255.255.0.

    ```
    >>> import random
    >>> random.seed("test0")
    >>> random.randint(2,254)
    209
    >>> random.seed("test1")
    >>> random.randint(2,254)
    184
    ```
    """
    if not args.network_id:
        return None
    subnet_mask = helper.interface[testing.VMNET_SUBNET_MASK]
    host_address = helper.interface[testing.VMNET_START_ADDRESS]
    if subnet_mask == "0.0.0.0" and host_address == "0.0.0.0":
        # This happens on macOS < 15, let's assign a random subnet
        # This will make tests flaky
        subnet_mask = "255.255.255.0"
        host_address = "192.168.55.1"
    interface = ipaddress.IPv4Interface(f"{host_address}/{subnet_mask}")
    net_addr = interface.network.network_address
    random.seed(args.vm_name)
    vm_offset = random.randint(2, interface.network.num_addresses - 1)
    return ipaddress.IPv4Interface(f"{net_addr + vm_offset}/{subnet_mask}")


if __name__ == "__main__":
    main()
