# SPDX-FileCopyrightText: The vmnet-helper authors
# SPDX-License-Identifier: Apache-2.0

---
name: Integration

on:
  workflow_call:  # Can be called from other workflows

permissions:
  contents: read

jobs:
  example:
    name: Example
    # macos-26 (arm64) is using M1 cpu but nested virtualization require M3 or
    # later.
    runs-on: macos-15-intel
    strategy:
      fail-fast: false
      matrix:
        driver: [vfkit, qemu]
        connection: [fd, socket, runner]
        exclude:
          - driver: qemu
            connection: socket
    steps:
      - name: Host info
        run: |
          uname -a
          sw_vers
          ifconfig
      - name: Disable spotlight indexing
        run: |
          # Disable indexing globally
          sudo mdutil -a -i off
          # Erase Existing Indexes
          sudo mdutil -E /
      - name: Install requirements
        run: brew install qemu cdrtools coreutils tree
      - name: Inspect qemu
        # Looking up both prefixes to make it eaier to port to arm64 in the future.
        run: |
          tree -h /usr/local/share/qemu || true
          tree -h /opt/homebrew/share/qemu || true
      - name: Install vfkit
        if: matrix.driver == 'vfkit'
        run: brew install vfkit
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Download build artifact
        uses: actions/download-artifact@v7
        with:
          name: vmnet-helper.tar.gz
      - name: Install vmnet-helper
        run: VMNET_INTERACTIVE=0 ./install.sh vmnet-helper.tar.gz
      - name: Print version
        run: /opt/vmnet-helper/bin/vmnet-helper --version
      - name: Ensure public key
        run: |
          ssh-keygen -q -N "" </dev/zero
      - name: Configure ssh
        run: |
          echo "Include ~/.vmnet-helper/vms/*/ssh.config" >> ~/.ssh/config
      - name: Create virtual env
        run: |
          python3 -m venv .venv
          .venv/bin/pip install pyyaml
      - name: Flush mDNS cache
        run: |
          sudo dscacheutil -flushcache
          sudo killall -HUP mDNSResponder
      - name: Start example VM
        run: |
          # NOTE: Run as root to allow mDNS resolution and checking guest
          # connectivity.  macOS Local Network Privacy blocks local network
          # access for non-root processes outside Terminal.
          sudo --preserve-env HOME=$HOME .venv/bin/python3 ./run test \
              --driver ${{ matrix.driver }} \
              --connection ${{ matrix.connection }} \
              --timeout 300 \
              --verbose &
          pid=$!
          echo $pid > test.pid
          if ! timeout 300s bash -c "until nc -z test-vmnet-helper.local 22 2>/dev/null; do true; done"; then
              echo >&2 "Timeout waiting for test-vmnet-helper.local"
              exit 1
          fi
      - name: Inspect VM host data
        if: always()
        run: |
          tree -h -D --timefmt '%Y-%m-%d %H:%M:%S' ~/.vmnet-helper
          vm="$HOME/.vmnet-helper/vms/test"
          vm_files=$(find "$vm" -name "*.command" -or -name "*.log")
          for f in $vm_files; do
            echo "==> $f <=="
            sudo head -n 500 "$f" || true
          done
          echo "==> /var/db/dhcpd_leases <=="
          ls -l /var/db/dhcpd_leases || true
          sudo head -n 500 /var/db/dhcpd_leases || true
      - name: Inspect VM guest data
        run: |
          echo "uname: $(ssh test -- uname -a)"
          echo "cmdline: $(ssh test -- cat /proc/cmdline)"
      - name: Prepare example VM
        run: |
          ssh test -- sudo apt-get update -y
          ssh test -- sudo DEBIAN_FRONTEND=noninteractive apt-get install -y iperf3
          ssh test -- sudo systemctl start iperf3.service
          echo "Waiting for iperf3 server ..."
          ssh test -- bash -s << EOF
            if ! timeout 10s bash -c "until ss -tln | grep -q :5201; do sleep 1; done"; then
              echo >&2 "Timeout waiting for iperf3 port"
              exit 1
            fi
          EOF
          echo "iperf3 server is ready"
      - name: Run iperf3 (host to vm)
        run: |
          iperf3-darwin -c test-vmnet-helper.local
      - name: Run iperf3 (vm to host)
        run: |
          iperf3-darwin -c test-vmnet-helper.local --reverse
      - name: Terminate example VM
        run: |
          pid=$(cat test.pid)
          echo "Terminating example (pid $pid)"
          sudo kill $pid
          echo "waiting for termination"
          for n in $(seq 20); do
              if ! sudo kill -s 0 $pid; then
                  echo "example terminated ($n/20)"
                  exit 0
              fi
              sleep 1
          done
          echo "timeout terminating example" >&2
          exit 1
      - name: Collect logs
        if: always()
        run: |
          vm="$HOME/.vmnet-helper/vms/test"
          find "$vm" -maxdepth 1 -type f \
              -not -name "*.img" \
              -not -name "*.iso" \
              -not -name "kernel" \
              -not -name "initrd" \
              > artifacts.txt
          test -f /var/db/dhcpd_leases && echo /var/db/dhcpd_leases >> artifacts.txt
          sudo tar --create --gzip \
              --file vmnet-helper-integration-${{ matrix.driver }}-${{ matrix.connection }}.tar.gz \
              --files-from artifacts.txt
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: vmnet-helper-integration-${{ matrix.driver }}-${{ matrix.connection }}
          path: vmnet-helper-integration-${{ matrix.driver }}-${{ matrix.connection }}.tar.gz
          compression-level: 0
